src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticlesRepository::class)
 */
class Articles
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=120)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="json")
     */
    private $ingredient=[];

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $duration;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_person;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $recipe_image;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=true)
     */
    private $users;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getIngredient(): ?array
    {
        $ingredient = $this->ingredient;
        $ingredient[] = '';

        return array_unique($ingredient);

        // return $this->ingredient;
    }

    public function setIngredient(array $ingredient): self
    {
        $this->ingredient = $ingredient;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getNbPerson(): ?int
    {
        return $this->nb_person;
    }

    public function setNbPerson(int $nb_person): self
    {
        $this->nb_person = $nb_person;

        return $this;
    }

    public function getRecipeImage(): ?string
    {
        return $this->recipe_image;
    }

    public function setRecipeImage(string $recipe_image): self
    {
        $this->recipe_image = $recipe_image;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }
}

src/Controller/RecipesController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ArticlesRepository;
use Doctrine\ORM\EntityManagerInterface;


class RecipesController extends AbstractController
{
    /**
     * la liste des recettes
     * @Route("/", name="recipes_index")
     */
    public function index(EntityManagerInterface $em): Response
    {
        $repository = $em->getRepository(Articles::class);

        return $this->render('recipes/index.html.twig', [
            'articles' => $repository->findAll(),
        ]);
    }
    

    /**
     *  ajouter une recette
     * @Route("/recipes/add", name="recipes_add")
     */
    public function add(EntityManagerInterface $em): Response
    {
        // On vérifie que mon formulaire soit rempli
        if(!empty ($_POST)){

            $post = array_map('trim', array_map('strip_tags', $_POST));

            $article = new Articles();  // Je prépare l'instance de classe (donc un objet)

            $formIsValid = $this->addEdit($em, $article);

            if ($formIsValid['status'] == false){
                
                foreach($formIsValid['errors'] as $error){
                    $this->addFlash('warning', $error);
                }
                
                return $this->render('recipes/add.html.twig',  [
                    'post' => $post ?? array()
                ]);
            }
            else{
                $this->addFlash('success', 'Modification effectuée');
                return $this->redirectToRoute('recipes_index');
            }    
        }

        return $this->render('recipes/add.html.twig',  [
            'post' => $post ?? array()
        ]);

    }

    /**
     * ajouter une recette
     * @Route("/recipes/edit/{id}", name="recipes_edit", methods={"POST","GET"} )
     */
    public function edit(EntityManagerInterface $em, int $id): Response
    {
        $article = $em->getRepository(Articles::class)->find($id); // Je récupère mon instance de classe via l'article trouvé

        if (!$article) {
            throw $this->createNotFoundException(
                'No product found for id ' . $id
            );
        }

        if(!empty ($_POST)){

            // fonction de vérification des valeurs du formulaire
            $formIsValid = $this->addEdit($em, $article);
            // Si on vérifie le status 
            if ($formIsValid['status'] == false){
                // le formulaire retourne des erreurs et on les affiche
                foreach($formIsValid['errors'] as $error){
                    $this->addFlash('warning', $error);
                }

                // redirection vers le formulaire edit avec les données existantes
                return $this->redirectToRoute('recipes_edit', [
                    'id' => $article->getId(),
                    'post' => $_POST
                ]);
            }
            else
            {
                // pas d'erreurs, et redirection vers la page show
                $this->addFlash('success', 'Modification effectuée');
                return $this->redirectToRoute('recipes_show', [
                    'id' => $article->getId(),
                    'article' => $article
                ]);
            }

        }
        return $this->render('recipes/edit.html.twig', [
            'id' => $article->getId(),
            'article' => $article
        ]);
    }



    /**
     * @Route("/recipes/show/{id}", name="recipes_show", methods={"GET"})
     */
    public function show(EntityManagerInterface $em, int $id): Response
    {
        $repository = $em->getRepository(Articles::class);
        return $this->render('recipes/show.html.twig', [
            'article' => $repository->findOneBy(['id' => $id]),
        ]);
    }

    private function addEdit(EntityManagerInterface $em, Articles $article) :array
    {
        $errors = [];
        $em = $this->getDoctrine()->getManager();
      
        if (!empty($_POST)) {

            $post = array_map('trim', array_map('strip_tags', $_POST));

            $formIsValid = $this->validForm($post);
            if ($formIsValid['status'] == false){
                // error
                $errors += $formIsValid['errors'];
            }
            else{
                $uploadIsValid =  $this->getCheckUpload($article);
                if ($uploadIsValid['status'] == false){
                    // error
                    $errors += $uploadIsValid['errors'];
                }
            }
            if(empty($errors)){
                // succes
                $article->setTitle($post['title']);
                $article->setContent($post['content']);
                $article->setIngredient([$post['ingredient']]);
                $article->setCreatedAt(new \DateTime());
                $article->setDuration($post['duration']);
                $article->setNbPerson($post['nb_person']);
                $article->setUsers($this->getUser());

                // Update de l'image que si elle existe ou si elle est différente
                if(!empty($article->getRecipeImage()) && $article->getRecipeImage() != $uploadIsValid['file']){
                    $article->setRecipeImage($uploadIsValid['file']);
                }
                elseif(empty($article->getRecipeImage())){ // Ajout
                    $article->setRecipeImage($uploadIsValid['file']);
                }

                // ajout 
                if(empty($article->getId())){
                    $em->persist($article);
                }
                $em->flush(); 
            }
        }
        
        // Ecriture ternaire (condition ) ? 'si vrai' : 'sinon'
        //return (!empty($errors)) ? ['status' => false, 'errors' => $errors] : ['status' => true, 'errors' => false];

        if(!empty($errors)){
            return [
                'status' => false, 
                'errors' => $errors
            ]; 
        }
        else  {
            return [
                'status' => true, 
                'errors' => []
            ];
        }
    }

    private function validForm(array $post):array
    {

        $errors =[];

        //On vérifie que le champs title est rempli
        if (empty($post['title'])) {
            $errors[] = ' Le champ Titre est invalide';
        }
        //On vérifie que le champs title a longueur comprise entre 5 et 120 caractères
        if (strlen($post['title']) < 5 || strlen($post['title']) > 120){
            $errors[] = 'La longueur du champ Titre est comprise entre 5 et 120 caractères';
        }
        //On vérifie que le champs content est rempli
        if (empty($post['content'])) {
            $errors[] = ' Le champ Contenu est invalide';
        }
        //On vérifie que le champs content a longueur minimum de 5 caractères
        if (strlen($post['content']) < 5){
            $errors[] = 'La longueur du champ Contenu est invalide';
        }
        //On vérifie que le champs ingredient est rempli
        if (empty($post['ingredient'])) {
            $errors[] = ' Le champ Ingredient est invalide';
        }
        //On vérifie que le champs ingredient a longueur minimum de 15 caractères
        if (strlen($post['ingredient']) < 15){
            $errors[] = 'La longueur du champ Ingredient est invalide';
        }
        //On vérifie que le champs duration est rempli et que le champs duration est un entier
        if ($post['duration'] <= 0 || !is_numeric($post['duration']) ) {
            $errors[] = ' Le champ Duree est invalide';
        }

        //On vérifie que le champs nb_person est rempli et que le champs nb_person est un entier
        if ($post['nb_person'] <= 0 || !is_numeric($post['nb_person']) ) {
            $errors[] = ' Le champ Nombre de personne est invalide';
        }

        // Si des erreurs sont détectés, on revoie un status à false et un tableau d'erreurs
        // sinon on revoie un status à true et un tableau d'erreurs vide
        return (!empty($errors)) ? ['status' => false, 'errors' => $errors] : ['status' => true, 'errors' => false];  
    }

    private function getCheckUpload(Articles $article) :array
    {
        $fichier = null;
        $errors =[];

        // cas add 
        if (!empty($_FILES)) {


            $target_dir = $this->getParameter('images_directory'). "/" ; // uploads directory
            $file = basename($_FILES['recipe_image']['name']);
            $target_file = $target_dir .$file;
            $max_size = 5242880;
            $size = $_FILES['recipe_image']['size'];
            $imageFileType = strtolower(pathinfo($target_file,PATHINFO_EXTENSION));
            $extensions = array('png', 'gif', 'jpg', 'jpeg');
            $tmp_name = $_FILES["recipe_image"]["tmp_name"];
            
            // verification de l'extension du fichier à uploader
            if (!in_array($imageFileType, $extensions)){
                $errors[] = "l'extension du fichier n'est pas reconnu ['png', 'gif', 'jpg', 'jpeg']" . $file;
            }

            // verification de la taille du fichier à uploader
            if ($size > $max_size){
                $errors[] = 'La taille du fichier dépasse la taille maxi ' . $max_size;
            }

            // Si pas d'erreurs, alors on upload le fichier
            if(count($errors) == 0)
            {
                // Génère un identifiant unique
                $fichier =  uniqid() . $imageFileType ;

                // On va copier le fichier dans le dossier upload
                $newfile = $target_dir . $fichier;
                if(!move_uploaded_file($tmp_name, $newfile)){
                    $errors[] = 'Une erreur grave est survenue';
                }
            }

        }
        else 
        {
            //   cas edit
            if ($article->getRecipeImage()){

templates/recipes/add.html.twig
{% extends 'base.html.twig' %}



{% block title %}Create new Articles{% endblock %}

{% block body %}
<div class="container" style="background-image: url('../media/etoile.jpg')">
    <div class="row justify-content-center">
        <div class="col-lg-7">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header" style="background-image: url('../media/etoile.jpg')";>
                    <h3 class="text-center font-weight-light my-4" style="color: beige;">Ajouter votre nouvelle recette</h3>
                </div>
                <div class="card-body" style="background-image: url('../media/etoile.jpg')">
                    <form method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="articles_title" class="required">Titre</label>
                            <input class="form-control form-control-lg" type="text" id="articles_title" value="{{ post.title ?? null }}"  name="title" required="required" maxlength="120" />
                        </div>
                        <div class="row my-3">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="articles_nb_person" class="required">Nombre de personne(s)</label>
                                    <input class="form-control form-control-lg" type="number" id="articles_nb_person" value="{{ post.nb_person ?? "" }}" name="nb_person" required="required" />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="articles_duration" class="required">Duration (en minutes)</label>
                                    <input class="form-control form-control-lg" type="number" id="articles_duration" value="{{ post.duration ?? "" }}" name="duration" required="required" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group my-3">
                            <label for="articles_ingredient" class="required">Ingrédient</label>
                            <textarea class="form-control form-control-lg" id="articles_ingredient" name="ingredient" required="required" style="height: 200px">{{ post.ingredient ?? null }}</textarea>
                        </div>

                        <div class="form-group my-3">
                            <label for="articles_content" class="required">Description de la recette</label>
                            <textarea class="form-control form-control-lg" id="articles_content" name="content" required="required"  style="height: 300px" >{{ post.content ?? null }}</textarea>
                        </div>

                        <div class="form-group my-3">
                            <label for="formFile" class="form-label">Ajouter une illustration</label>
                            <input class="form-control" name="recipe_image" type="file" id="formFile">
                        </div>

                        <div class="form-group my-3" style="display: flex;justify-content: space-around;">
                            <button type="submit" class="btn btn-primary btn-block mt-5">Ajouter </button>
                            <a class="btn bg-light btn-block mt-5" href="{{ path('recipes_index') }}">Annuler</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/recipes/delete.html.twig
{% extends 'base.html.twig' %}



{% block title %}Supprimer la recette{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6">
            <form method="post">
                <p> Vous êtes sur le point de supprimer la recette 
                <br>&laquo; {{recipe.title}} &raquo;</p>
                <p> Attention la suprresion est définitive !!!</p>


                <div class="form-group my-3">

                    <a class="btn bg-light btn-block mt-5" href="{{ path('recipes_index') }}">Annuler</a>
                    <input type="hidden" name="confirm" value="yes">
                    <button type="submit" class="btn btn-primary btn-block mt-5">Supprimer </button>



                </div>


            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/recipes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des recettes{% endblock %}

{% block body %}
    <h1>Articles index</h1>

    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Modification de recette</h3>
                        </div>
                        <div class="card-body">
                            <form method="post">
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="inputFirstName">Titre</label>
                                            <input class="form-control py-4" id="inputFirstName" name="title"
                                                type="text" placeholder="Titre" value="{{ article.title }}"/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                    <label class="small mb-1" for="inputEmailAddress">Durée</label>
                                    <input class="form-control py-4" id="inputEmailAddress" name="duration" value="{{ article.duration }}"/>
                                </div>
                                 <div class="form-group">
                                    <label class="small mb-1" for="inputEmailAddress">Nombre de personnes</label>
                                    <input class="form-control py-4" id="inputEmailAddress" name="nb_person" value="{{ article.nbPerson }}"/>
                                </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="inputLastName">Ingredients</label>
                                            <textarea class="form-control py-4" id="inputLastName" name="ingredient"
                                                type="text"  />{{ article.ingredient }}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group">
                                        <label class="small mb-1" for="inputMessage">Contenu</label>
                                        <textarea class="form-control py-4" id="inputMessage" name="content"
                                            placeholder="Ecrivez votre recette">{{ article.content }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0"><button type="submit" class="btn btn-info">Envoyer</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </main>
      
 <a href="{{ path('recipes_add') }}">Ajout d'une nouvelle recette</a>
 <a href="{{ path('recipes_index') }}">Toutes les recettes</a>
{% endblock %}

templates/recipes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'accueil
{% endblock %}

{% block body %}

	<nav class="navbar navbar-expand-lg navbar-light bg-danger">
		<div class="container-fluid">
			<a class="navbar-brand" href="">
				<i class="las la-pizza-slice"></i>Bienbouffer.com</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" id="link" href="{{ path('recipes_add') }}">Ajouter une nouvelle recette</a>
					</li>
				
					{% if app.user %}
						<li class="nav-item dropdown">
							<a
								class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								 Bonjour {{ app.user.firstname }}{# <i class="fa fa-user"></i> <?= $_SESSION['user']['firstname'] ?> #}
							</a>

							<ul
								class="dropdown-menu" aria-labelledby="navbarDropdown">
								{# <li><a class="dropdown-item" href="profil.php">Mon profil</a></li> #}
								<li>
									<hr class="dropdown-divider">
								</li>
								<li>
									<a class="dropdown-item" href="{{ path('app_logout') }}">
										<i class="material-icons">&#xE8AC;</i>Se déconnecter</a>
								</li>
							</ul>

						</li>
					{% else %}

						<li class="nav-item">
							<a class="nav-link" href="{{ path('app_register') }}">S'inscrire</a>
						</li>
						<li class="nav-item">
							<a id="connect" class="nav-link" href="{{ path('app_login') }}">Connexion</a>
						</li>

					{% endif %}


				</ul>
			</div>
		</div>
	</nav>


	<section class="container">
		<div
			class="row">
			{# Insertion de la boucle article pour tous les afficher #}
			{% for article in articles %}
				<article class="card col-sm-5 text-white bg-danger m-3" style="max-width: 40rem;">
					<div class="card-header">{{ article.createdAt ? article.createdAt|date('d-m-Y H:i') : '' }}</div>
					<div class="card-body">
						<h5 class="card-title">{{ article.title }}</h5>
						<p><img class="card-img-top img-fluid" src="{{asset('/uploads/' ~ article.recipeImage)}}" alt="Image" width="175"></p>
						<p class="card-text text-center">
							<button id="btnwhite" type="button" class="btn btn btn-outline-light ">
								<a href="{{ path('recipes_show', {'id': article.id}) }}">Détails</a>
							</button>

							{% if is_granted('ROLE_ADMIN') or (app.user and  app.user.id == article.users.id) %}

								<button id="btnwhite" type="button" class="btn btn-outline-light ">
									<a href="{{ path('recipes_edit', {'id': article.id}) }}">Modifier</a>
								</button>
							{% endif %}
						</p>
					</div>
				</article>
			{% endfor %}
		</div>
	</section>


{% endblock %}

templates/recipes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails de la recette{% endblock %}

{% block body %}
<!-- Receipe Slider -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <img src="{{asset('/uploads/' ~ article.recipeImage)}}" alt="Image" width="150">
        </div>
    </div>
</div>

<!-- Receipe Content Area -->
<div class="receipe-content-area d-flex m-auto w-75">
    <div class="container m-auto">

        <div class="row">
            <div class="col-12 col-md-8">
                <div class="receipe-headline my-5">
                    <h1 class="text-center text-uppercase p-5">{{ article.title }} </h1>
                    <span class="mb-5">Publié le
                        {{ article.createdAt ? article.createdAt|date('d/m/Y H:i') : '' }}</span>

                    <div class="border-start border-success border-4 m-4 p-2">
                        <h6>Prep: {{ article.duration }} minutes</h6>

                        <h6>{{ article.nbPerson }} personnes</h6>
                    </div>
                </div>
            </div>

        </div>
        <div class="row mb-5">
            <!-- Ingredients -->
            <div class="col-12 col-lg-4">
                <div class="ingredients">
                    <h4 class="text-danger fw-bold"><u>Ingrédients</u></h4>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        {% for ingredient in article.ingredient %}
                        <p>{{ ingredient}} </p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-lg-8">
                <!-- Single Preparation Step -->
                <h4 class="text-danger fw-bold"><u>Préparation</u></h4>
                <div class="single-preparation-step d-flex">
                    {# <h4>01.</h4> #}
                    <p> {{ article.content|nl2br }} </p>
                </div>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-12 col-lg-8">
                <a href="{{ path('recipes_index') }}">Voir toutes les recettes</a>

            </div>
        </div>
    </div>
</div>
{% endblock %}